language: python

php:
  - 2.7

install: "pip install -r requirements.txt"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: ls functional-tests/*py | while read ln; do python $ln; done